Repository Hold-Krykke/3SemProject_FrontEnd, pull requests merged in 2019-12, with the labels that each got.

#32 Old SVG deleted from master
  src/svg_files/Europe.js
Labels: SPRINT 2

#31 City data and comments/cleanup
  src/components/EuropeMap.jsx
  src/components/MapViewer.jsx
Labels: SPRINT 2

#30 US#7 frontend
  src/apiFacade.js
  src/components/Result.jsx
  src/settings.js
Labels: SPRINT 2

#39 Update README.md
  README.md
Labels: SPRINT 3

#38 About&Credit
  src/App.js
  src/components/About.jsx
  src/components/EuropeMap.jsx
  src/components/Footer.jsx
Labels: SPRINT 3

#37 Issue#7 date-logic/endpoint functionality
  src/apiFacade.js
  src/components/Result.jsx
Labels: SPRINT 3

#43 Updated Result component and fixed a few bugs
  src/components/Result.jsx
Labels: SPRINT 3, bug

#44 Issue #41 fixed
  src/components/About.jsx
Labels: SPRINT 3, bug

#46 Tying all components together
  src/App.js
  src/components/City.jsx
  src/components/Date.jsx
  src/components/EuropeMap.jsx
  src/components/Header.jsx
  src/components/Result.jsx
Labels: SPRINT 3

#36 Date picker bug
  src/components/EuropeMap.jsx
Labels: SPRINT 3, bug

#45 georgia, armenia and turkey deleted
  src/components/MapViewer.jsx
Labels: DON'T MERGE, SPRINT 3, bug

#42 US#7 - Errorhandling, minor fixes [Weather]
  src/App.js
  src/components/Result.jsx
Labels: SPRINT 3

#40 Applying styles
  src/components/About.jsx
  src/components/AboutStyles.css
  src/components/Date.jsx
  src/components/DateStyles.css
  src/components/EuropeMap.jsx
  src/components/EuropeMapStyles.css
  src/components/Footer.jsx
  src/components/FooterStyles.css
  src/components/Header.jsx
  src/components/HeaderStyles.css
  src/components/Icons/CrutchIcon.js
  src/components/Icons/DateIcon.js
  src/components/Icons/GithubIcon.js
  src/components/Icons/HeaderArrow.js
  src/components/Icons/LocationIcon.js
  src/components/Icons/index.js
  src/components/MapViewer.jsx
  src/components/Result.jsx
  src/components/ResultStyles.css
  src/index.css
Labels: SPRINT 3

#48 Update README.md
  README.md
Labels: SPRINT 3
