Repository Hold-Krykke/3SemProject_FrontEnd, pull requests merged in 2019-11, with the labels that each got.

#12 Init setup for frontend
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/index.css
  src/index.js
Labels: SPRINT 1

#13 Europe view onclick
  package-lock.json
  src/App.js
  src/components/EuropeMap.jsx
  src/svg_files/Europe.js
Labels: SPRINT 1

#14 Display name of country
  src/apiFacade.js
  src/components/EuropeMap.jsx
  src/settings.js
Labels: DON'T MERGE, SPRINT 1

#16 Updated settings and APIfacade
  src/apiFacade.js
  src/settings.js
Labels: SPRINT 1

#18 Routing + Header/Footer
  src/App.js
  src/components/City.jsx
  src/components/Date.jsx
  src/components/EuropeMap.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Result.jsx
Labels: SPRINT 1

#20 Added a Deployment Script for Surge
  package.json
Labels: SPRINT 1

#22 Date Component
  package-lock.json
  package.json
  src/App.js
  src/apiFacade.js
  src/components/Date.jsx
  src/components/Result.jsx
Labels: SPRINT 2

#23 Map changed & Asgers functionality is intact (minor color issue)
  src/App.js
  src/components/EuropeMap.jsx
  src/svg_files/Europe.js
Labels: SPRINT 2

#24 US#4 - Events (Results) Overview
  src/components/Result.jsx
Labels: SPRINT 2

#29 Fix issue with singular days/months
  src/apiFacade.js
  src/components/Result.jsx
  src/utilities.js
Labels: SPRINT 2, bug

#28 Zoom and pan functionality
  src/components/EuropeMap.jsx
  src/components/MapViewer.jsx
  src/svg_files/Europe.js
Labels: DON'T MERGE, SPRINT 2
